### ISSUE TITLE
please list requirements

### ISSUE THREAD

**Issue by bbaassssiiee** [arnabsinha4u/ansible-traininglab#1]
On Centos 7 I had to `yum install python-pip` to be able to `pip install docker-py`, only to find out that :
```
TASK [Build Master and Slave Images (Module)] **********************************
failed: [localhost] (item=master) => {"failed": true, "item": "master", "msg": "Error: docker-py version is 1.10.6. Minimum version required is 1.7.0."}
failed: [localhost] (item=slave) => {"failed": true, "item": "slave", "msg": "Error: docker-py version is 1.10.6. Minimum version required is 1.7.0."}
```

This logic is beyond my grasp.

**Comment by bbaassssiiee** [comment]
Updating to ansible-2.2:
TASK [Build Master and Slave Images (Module)] **********************************
failed: [localhost] (item=master) => {"failed": true, "item": "master", "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))"}
failed: [localhost] (item=slave) => {"failed": true, "item": "slave", "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))"}

**Comment by bbaassssiiee** [comment]
Ran `systemctl start docker`, now running the playbooks as root returns: ok=14   changed=10

**Comment by arnabsinha4u** [comment]
There are already couple of tasks as: Baseline Machine and Start Docker Engine.
These can be executed by selecting the baseline tag.
Did this not work for you?

**Comment by bbaassssiiee** [comment]
I tried but software was not up2date, not installed, or not running.

**Comment by arnabsinha4u** [comment]
If baseline is executed then its baselines the complete machine with dependencies. Specific install and starting of docker is not required. Tried it in Centos7 Minimal VagrantBox (3.10.0-229.el7.x86_64).

Thus I will remove the requirements line from the README and rather include the requirements.txt as a best practice.

[root@localhost ansible-traininglab]# history
    1  ll
    2  ls -ltr
    3  ifconfig
    4  which git
    5  git clone https://github.com/arnabsinha4u/ansible-traininglab.git
    6  ll
    7  which ansible
    8  yum install ansible
    9  rpm -iUvh http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm
   10  yum -y install ansible
   11  ll
   12  cd ansible-traininglab/
   13  ll
   14  ./ansible_lab.yml --tags=baseline
   15  ./ansible_lab.yml --tags=m_startup

CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                   NAMES
acd7a4c3eb23        ansible_lab/slave:latest    "/bin/sh -c '/usr/bin"   10 seconds ago      Up 8 seconds        0.0.0.0:32769->22/tcp   master-1-slave-1
ff714673b12a        ansible_lab/master:latest   "/bin/sh -c '/usr/bin"   12 seconds ago      Up 10 seconds       0.0.0.0:32768->22/tcp   master-1
